#include <lux/cxx/ct_string.hpp>
#include <cstdint>

namespace lux::cxx
{
	template<ct_string_type Name> struct name_type_of;
	template<class T> struct type_name_of;

#define __CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(_type) \
template<> struct name_type_of<MAKE_CT_STRING_TYPE( #_type )> {\
	using type = _type;\
};

#define __CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(_type) \
template<> struct type_name_of<_type> {\
	using name = MAKE_CT_STRING_TYPE( #_type );\
};

	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(void)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(void)

	// Character types
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(char)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(wchar_t)

	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(char)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(wchar_t)

	// ------------- all available integer types -------------
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed char)

	// unsigned char
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned char)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(unsigned char)

	// short int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(short)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(short int)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed short)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed short int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(short int)

	// unsigned short int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned short)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned short int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(unsigned short int)

	// int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(int)

	// unsigned int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(unsigned int)

	// long int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(long)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(long int)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed long int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(long int)

	// unsigned long int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned long)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned long int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(unsigned long int)

	// long long int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(long long)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(long long int)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed long long)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(signed long long int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(long long int)

	// unsigned long long int
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned long long)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(unsigned long long int)
	__CXX_NAME_FUNDAMENTAL_TYPE_NAME_DEFINE(unsigned long long int)
	// ------------- all available integer types -------------

	// Fixed width integer types
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int8_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int16_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int32_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int64_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_fast8_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_fast16_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_fast32_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_fast64_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_least8_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_least16_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_least32_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(int_least64_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(intmax_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(intptr_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint8_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint16_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint32_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint64_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_fast8_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_fast16_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_fast32_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_fast64_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_least8_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_least16_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_least32_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uint_least64_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uintmax_t)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(uintptr_t)

	// bool
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(bool)

	// float
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(float)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(double)
	__CXX_NAME_FUNDAMENTAL_NAME_TYPE_DEFINE(long double)
}
