add_executable(core_test core_test.cpp)
target_link_libraries(core_test PRIVATE lux::cxx::core)
target_compile_features(core_test PRIVATE cxx_std_20)
add_test(NAME core_test COMMAND core_test)

add_executable(format_test format_test.cpp)
target_link_libraries(format_test PRIVATE lux::cxx::core)
target_compile_features(format_test PRIVATE cxx_std_20)
add_test(NAME format_test COMMAND format_test)

add_executable(noexcept_function_test noexcept_function_test.cpp)
target_link_libraries(noexcept_function_test PRIVATE lux::cxx::core)
target_compile_features(noexcept_function_test PRIVATE cxx_std_20)
if(MSVC)
    foreach(target core_test format_test noexcept_function_test)
        target_compile_options(${target} PRIVATE /UNDEBUG /permissive-)
    endforeach()
else()
    foreach(target core_test format_test noexcept_function_test)
        target_compile_options(${target} PRIVATE -UNDEBUG)
    endforeach()
endif()
add_test(NAME noexcept_function_test COMMAND noexcept_function_test)
